### ISSUE TITLE
Can't use useSnackbar inside Stage, it works everywhere else ( please take a look at the demo)

### ISSUE THREAD

**Issue by nnha19** [konvajs/konva#1419]
I am using notisnack to display the error message when rectangle is resized and if the size is too small. But, it's not working inside the Stage. Can you help me figure out why it doesn't work? It's working in the entire app but just inside the stage

This is what it said
```
Cannot read properties of undefined (reading 'getParent')
```

**Demo Link**
https://codesandbox.io/s/priceless-monad-iqlp9c?file=/src/index.js

**Comment by lavrton** [comment]
Working version: https://codesandbox.io/s/falling-tree-d9501n?file=/src/index.js

What I did:

1. Wrapped whole stage into Provider. It looks like the provider was rending some DOM elements, and react-konva don't like it, because it is canvas rendering.
2. Removed `<div>` from `Rectangle` component. You can't use DOM elements inside canvas. If you really need it take a look into `Html` component in `react-konva-utils`.
3. Updated `react-konva` to automatically support for context bridge.

**Comment by nnha19** [comment]
I also updated react-konva to the latest version **("react-konva": "^18.2.2",)** and it breaks as soon as I open up the page in my project. 

```
index.tsx:96 Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_0__.useId is not a function
    at useFiber (index.tsx:96:1)
    at useContextBridge (index.tsx:196:1)
    at StageWrap (ReactKonvaCore.js:28:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
```

**Comment by lavrton** [comment]
Did you look in the demo? It works ok. Also check react and react-dom versions.

**Comment by rishab-sharma** [comment]
@lavrton I am alsi seeing the same error message
`Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_0__.useId is not a function`

"react-konva": "^18.2.2",
"konva": "^8.3.13"
"react": "^17.0.2",
"react-dom": "^17.0.2",

**Comment by lavrton** [comment]
Update `react` and `react-dom` to the last one.
