### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by CheMingjun** [konvajs/konva#1460]
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

in react code:

```tsx
<Group opacity={0.2}/>
```

Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at SceneContext.drawImage (http://localhost:8000/index.js:231489:16)
    at Rect.drawScene (http://localhost:8000/index.js:234405:15)
    at http://localhost:8000/index.js:231202:24
    at Array.forEach (<anonymous>)
    at Group._drawChildren (http://localhost:8000/index.js:231201:66)
    at Group.drawScene (http://localhost:8000/index.js:231147:12)
    at http://localhost:8000/index.js:231202:24
    at Array.forEach (<anonymous>)
    at Group._drawChildren (http://localhost:8000/index.js:231201:66)
    at Group.drawScene (http://localhost:8000/index.js:231147:12)

**Comment by lavrton** [comment]
Can you make a full demo? What do you have inside code? Looks like you have something with zero size.

**Comment by darkxanter** [comment]
I get the same error when adding a rectangle with opacity < 1 when layer size is 0, but rectangle with opacity 1 is added without error when layer size is 0.

**Comment by CheMingjun** [comment]
> Can you make a full demo? What do you have inside code? Looks like you have something with zero size.


<Group>
    <Group opacity={0.5} width={100}  width={100}/>
    <Group opacity={1} width={100}  width={100}/>
</Group>

**Comment by CheMingjun** [comment]
If use code like this ,it will work

```tsx
    <Group
      ref={el => {
        if (el) {
            setTimeout(v => {
              el.opacity(0.5)
            }, 1000)
        }
      }}
   width={100} height={100}/>
```

**Comment by CheMingjun** [comment]
@lavrton how to resolve the problem

**Comment by maaft** [comment]
I also observe a similiar issue:

```typescript
<Layer opacity={0.2}>
   {someShapes}
</Layer>
```

Application crashes with:
```
react-dom.development.js:11340 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at SceneContext.drawImage (http://localhost:3000/static/js/vendors~main.chunk.js:104140:16)
    at Line.drawScene (http://localhost:3000/static/js/vendors~main.chunk.js:107722:15)
    at http://localhost:3000/static/js/vendors~main.chunk.js:103791:24
    at Array.forEach (<anonymous>)
    at Group._drawChildren (http://localhost:3000/static/js/vendors~main.chunk.js:103790:66)
    at Group.drawScene (http://localhost:3000/static/js/vendors~main.chunk.js:103720:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:103791:24
    at Array.forEach (<anonymous>)
    at Layer._drawChildren (http://localhost:3000/static/js/vendors~main.chunk.js:103790:66)
    at Layer.drawScene (http://localhost:3000/static/js/vendors~main.chunk.js:103720:12)
    at Layer.drawScene (http://localhost:3000/static/js/vendors~main.chunk.js:105360:81)
    at Layer.draw (http://localhost:3000/static/js/vendors~main.chunk.js:106991:10)
    at Stage.add (http://localhost:3000/static/js/vendors~main.chunk.js:108318:11)
    at appendChildToContainer (http://localhost:3000/static/js/vendors~main.chunk.js:532295:20)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:3000/static/js/vendors~main.chunk.js:549703:11)
```

**Comment by lavrton** [comment]
Still no demo provided. I am going to close the issue.

The error clearly says that something has 0 size. Check it. Check size of stage or images.
If you still have an issue. Make online demo with codesanbox that clearly shows the issue.
