### ISSUE TITLE
canvas not marked as a dependency

### ISSUE THREAD

**Issue by tylerlaws0n** [konvajs/konva#1791]
I can create a reproduction of this if necessary, but I think it is easy enough to just explain here.

From the build output of this library in the `lib/index-node.js` file:

```js
const Canvas = require("canvas");
```

With requiring another module, this should be marked as a "dependency" or "peerDependency" in the package.json, but is currently a devDependency. This then relies on consumers of konva to see an error like the following at their build or runtime: 

```
Error: Cannot find module 'canvas'
Require stack:
- /opt/app/node_modules/konva/lib/index-node.js
- /opt/app/node_modules/react-konva/lib/ReactKonva.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /opt/app/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/opt/app/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/app/node_modules/konva/lib/index-node.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/opt/app/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/app/node_modules/react-konva/lib/ReactKonva.js:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/app/node_modules/konva/lib/index-node.js',
    '/opt/app/node_modules/react-konva/lib/ReactKonva.js'
  ]
}
```

and then manually install `canvas` for it to become available.

I'd personally prefer dependency over peerDependency because peerDeps are no longer automatically installed and instead just warn, but with it only being a devDep, it won't fail until running the code.

Happy to help make changes or clarify things however I can btw :)

**Comment by lavrton** [comment]
`canvas` library is not defined in dependencies intentionally. `canvas` is used in node.js environment. But major part of `npm` installations and general use case for `konva` is **browser-only** target. To make the installation smaller, `canvas` is not listed in `dependencies`.

The most common use case when users have this problem is when they use `react-konva` in next.js with SSR rendering.
In that scenario, I think the "client-only" approach should be used for canvas content, so again, `canvas` library should not be used/loaded/installed.

**Comment by lavrton** [comment]
Solution for next.js: https://github.com/konvajs/react-konva?tab=readme-ov-file#step-1---create-canvas-component
Solution ofr node.js env - just install `canvas` manually.

**Comment by tylerlaws0n** [comment]
I see, thanks for the thorough explanation!
