### ISSUE TITLE
Error raised during web pack

### ISSUE THREAD

**Issue by emlynmac** [konvajs/konva#266]
JSDOM issue during build:
```
/webpack:/~/Konva/konva.js:271
})(typeof global !== 'undefined' ? global : window);
 ^
TypeError: JSDOM is not a constructor
    at webpack:/~/Konva/konva.js:253:1
    at Object.<anonymous> (webpack:/~/Konva/konva.js:271:2)
    at __webpack_require__ (webpack:/webpack/bootstrap bf78ed29f58fa0723a17:19:1)
    at Object.module.exports.PI_OVER_180 (webpack:/components/AlgorithmNodes/Konva/IntermediateNode.jsx:1:1)
    at __webpack_require__ (webpack:/webpack/bootstrap bf78ed29f58fa0723a17:19:1)
    at Object.module.exports.Object.defineProperty.value (/webpack:/containers/AlgorithmLayout/AlgorithmLayout.jsx:8:1)
    at __webpack_require__ (webpack:/webpack/bootstrap bf78ed29f58fa0723a17:19:1)
    at Object.module.exports.Object.defineProperty.value (/compiled/server.dev.js:1307:26)
    at __webpack_require__ (/compiled/webpack:/webpack/bootstrap bf78ed29f58fa0723a17:19:1)
    at Object.<anonymous> (/webpack:/routes.jsx:3:1)
```
Node version 6.10.3
JSDom is version 8.5.0
Konva is version 1.6.8
Canvas is version 1.3.14

I originally was using react-konva and had it all working fine. I've removed that package and will render with konva directly due to performance issues.  

Is there something I'm missing that's giving me this issue?

Thanks in advance,

**Comment by lavrton** [comment]
Do you build it for client-frontend usage? If so, you don't `JSDom`, `Canvas`. They should be ignored by webpack.

**Comment by emlynmac** [comment]
I just did:

```
npm install konva
```

I'm also seeing:
```
Konva instance is already exist in current eviroment. Please use only one instance.
```

I don't see where I'm instantiating it at all - just using new Konva.Stage() and then Layer and adding things to layers.

**Comment by lavrton** [comment]
This message means that you have two copies of Konva code on the page. Added it twice?

**Comment by emlynmac** [comment]
Yeah, I was looking for that issue. My bad, turns out that I had included 'Konva' and 'konva'. As a result it went in twice... This was only revealed after I updated JSDOM to version 11.2.0 and the error message mentioned something about duplicates with case-sensitivity.

Thanks for responding so quickly, this ticket can be closed.
