### ISSUE TITLE
Konva.document.createWIndow() raises an error: "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by cactis** [konvajs/konva#36]
When test konva.js in nodejs environment

```js
$ node nodejs-demo.js
/Users/ctslin/temp/konvajs/konva/dist/konva-dev.js:604
            Konva.window = Konva.document.createWindow();
                                          ^
TypeError: undefined is not a function
    at /Users/ctslin/temp/konvajs/konva/dist/konva-dev.js:604:43
    at Object.<anonymous> (/Users/ctslin/temp/konvajs/konva/dist/konva-dev.js:621:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ctslin/temp/nodejs-demo.js:2:13)
    at Module._compile (module.js:460:26)
```

```
$ npm list jsdom
└── jsdom@4.0.2

$npm list konva
└── konva@0.9.0
``

thanks for your help.

**Comment by cactis** [comment]
after updating, got anohter error:

```js
$ node nodejs-demo.js
/Users/ctslin/temp/konva/dist/konva-dev.js:606
            Konva.window.Image = Canvas.Image;
                               ^
TypeError: Cannot set property 'Image' of undefined
    at /Users/ctslin/temp/konva/dist/konva-dev.js:606:32
    at Object.<anonymous> (/Users/ctslin/temp/konva/dist/konva-dev.js:622:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ctslin/temp/nodejs-demo.js:2:13)
    at Module._compile (module.js:460:26)
```

Konva.window is undefined.

thanks for your help.

**Comment by lavrton** [comment]
Hm.. What is versions of `nodejs`, `jsdom`?

**Comment by cactis** [comment]
```js
$ npm list jsdom
..
└── jsdom@4.0.2 

$ node --version
v0.12.0
```
thanks

**Comment by lavrton** [comment]
I can not install node v0.12 right now. Can you try `jsdom` v3? like:
```bash
npm install uninstall jsdom
npm install jsdom@3.x
```

**Comment by cactis** [comment]
it works! 
thanks for your help.

**Comment by lavrton** [comment]
Nice. Need to look into new version of `jsdom`.

**Comment by cactis** [comment]
How to use this version (0.9.5) for deploying to Heroku? 
thanks.

**Comment by lavrton** [comment]
- wait for a new release

or
- download `konva.js` manually and use it without npm

or
- `npm install git+https://git@github.com/konvajs/konva.git`

**Comment by cactis** [comment]
thanks~

**Comment by lavrton** [comment]
I updated installation instructions and tested. All works for `jsdom v3`.

**Comment by erinrosenbaum** [comment]
I'm still getting this problem. I uninstalled and reinstalled jsdom v3 and I am still getting the error. Thanks for the help

**Comment by lavrton** [comment]
@erinrosenbaum I updated Konva to work with latest versions of dependencies. Last tested with node@5.10.1, canvas@1.3.14, jsdom@8.5.0.
