### ISSUE TITLE
Error at draw time, when you cache very small shape

### ISSUE THREAD

**Issue by alpertuna** [konvajs/konva#392]
When you cache a small shape like this circle with `0.1px` radius;
```javascript
const stage = new Konva.Stage({
  container: 'container',
  width: window.innerWidth,
  height: window.innerHeight
});

const layer = new Konva.Layer();
stage.add(layer);

const circle = new Konva.Circle({
  x: stage.width() / 2,
  y: stage.height() / 2,
  radius: .1,
  fill: 'black'
});
circle.cache();
layer.add(circle);

layer.draw();
```
It throws this error at draw time;
```
"Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Konva.SceneContext.drawImage (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:1783:26)
    at Konva.Circle._drawCachedSceneCanvas (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:2611:21)
    at Konva.Circle.drawScene (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:7528:22)
    at https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:7031:34
    at Konva.Collection.each (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:308:13)
    at Konva.Layer._drawChildren (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:7030:27)
    at Konva.Layer.drawScene (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:6978:26)
    at Konva.Layer.drawScene (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:9931:49)
    at Konva.Layer.draw (https://cdn.rawgit.com/konvajs/konva/1.2.1/konva.js:4139:18)
    at gabuzokojo.js:21:7"
```

Actually my shapes are not small that much. I realize this problem when I run my app on a scaled view port because of low resolution screen.

I cannot catch error in order to remove or hide problem child, because it is thrown at batch drawing time and all drawing is stopped.

**Comment by lavrton** [comment]
Hmmm. I am not sure what can we do here from Konva part. Why do you cache so small shape?

**Comment by alpertuna** [comment]
This is a space ship game. There are randomly generated stars at background and they slightly move as ship moves. And I'am caching stars. Minimum star radius is 0.5 px and diameter is 1px. Until here there is no problem. However when I scale down browser view port to %90 from %100 and reinit the application, render is stopped because of this little stars. Sometimes it never crashes thank to all random stars are big enough.
The solution looks like not caching them for me. Furthermore this may be not an issue.
On the other hand, for Konva part, the solution may be making it an empty node if image width is zero after cache.

**Comment by lavrton** [comment]
Looks like canvas cannot render an image with super small size (like 0.3x0.2). It is rounding the size to 0x0 and throw the error.
